@include('layout.head')
@include('layout.topbar')
@include('layout.sidebar')
<div class="content"><div class="container-fluid">
<div class="mc-page-header"><div><h1 class="mc-page-title">Daily Report</h1><p class="mc-page-subtitle">Ringkasan konsumsi harian beserta transaksi terakhir.</p></div><div class="mc-page-actions"><a id="dExport" class="btn btn-primary" href="{{ route('consumptionData.export', ['period'=>now()->format('Y-m-d')]) }}"><i class="mdi mdi-microsoft-excel me-1"></i>Export Existing Excel</a></div></div>
<div class="mc-filterbar"><div class="mc-filter-field"><label class="mc-filter-label">Report Date</label><input id="dDate" type="date" class="form-control" value="{{ now()->format('Y-m-d') }}"></div><button id="dApply" class="btn btn-primary">Generate</button></div>
<div class="mc-stat-grid"><div class="mc-stat-card"><div class="mc-stat-label">Total Portions</div><div id="dTotal" class="mc-stat-value">—</div><div class="mc-stat-meta">All meals</div></div><div class="mc-stat-card is-success"><div class="mc-stat-label">Breakfast</div><div id="dBreakfast" class="mc-stat-value">—</div><div class="mc-stat-meta">Breakfast portions</div></div><div class="mc-stat-card is-orange"><div class="mc-stat-label">Lunch</div><div id="dLunch" class="mc-stat-value">—</div><div class="mc-stat-meta">Lunch portions</div></div><div class="mc-stat-card is-cyan"><div class="mc-stat-label">Dinner</div><div id="dDinner" class="mc-stat-value">—</div><div class="mc-stat-meta">Dinner portions</div></div></div>
<div class="mc-grid-2"><div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Daily Transactions</div><div id="dMeta" class="mc-panel-subtitle">Loading…</div></div></div><div class="table-responsive"><table class="mc-table-modern"><thead><tr><th>Time</th><th>NIK / Visitor</th><th>Meal</th><th>Order Type</th><th>Qty</th><th>Rating</th><th>Location</th></tr></thead><tbody id="dBody"></tbody></table></div></div><div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Order Type Summary</div><div class="mc-panel-subtitle">Portions by service type</div></div></div><div class="mc-panel-body" id="dOrders"></div></div></div>
</div></div>
<script>const de=v=>$('<div>').text(v??'').html();function dBars(rows){const t=rows.reduce((s,x)=>s+Number(x.total),0)||1;return rows.map(x=>`<div class="mc-progress-row"><div class="mc-progress-name">${de(x.name)}</div><div class="mc-progress-track"><div class="mc-progress-fill" style="width:${Number(x.total)/t*100}%"></div></div><div class="mc-progress-value">${x.total}</div></div>`).join('')||'<div class="mc-empty">No data</div>'}function loadD(){const date=$('#dDate').val();$('#dExport').attr('href',`{{ route('consumptionData.export') }}?period=${encodeURIComponent(date)}`);fetch(`{{ route('reports.daily.api') }}?date=${encodeURIComponent(date)}`).then(r=>r.json()).then(d=>{$('#dTotal').text(d.summary.total);$('#dBreakfast').text(d.summary.breakfast);$('#dLunch').text(d.summary.lunch);$('#dDinner').text(d.summary.dinner);$('#dMeta').text(`${d.summary.transactions} transactions · Avg rating ${Number(d.summary.average_rating).toFixed(1)}`);$('#dOrders').html(dBars(d.order_types));$('#dBody').html(d.records.length?d.records.map(x=>`<tr><td>${x.attendance_time?new Date(x.attendance_time).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):'—'}</td><td><strong>${de(x.nik||'Visitor')}</strong><div class="text-muted" style="font-size:9px">${de(x.visitor_name||'')}</div></td><td>${de(x.meal_type)}</td><td>${de(x.order_type||'—')}</td><td>${x.quantity}</td><td>${Number(x.rating||0)>0?`<span class="mc-stars">★</span> ${x.rating}`:'—'}</td><td>${de(x.position||'—')}</td></tr>`).join(''):'<tr><td colspan="7"><div class="mc-empty">No transactions</div></td></tr>');});}$('#dApply').click(loadD);loadD();</script>
@include('layout.footer')
