@include('layout.head')
@include('layout.topbar')
@include('layout.sidebar')
<div class="content"><div class="container-fluid">
<div class="mc-page-header"><div><h1 class="mc-page-title">Employee History</h1><p class="mc-page-subtitle">Cari histori konsumsi berdasarkan NIK tanpa mengubah data transaksi.</p></div></div>
<div class="mc-filterbar"><div class="mc-filter-field flex-grow"><label class="mc-filter-label">Employee NIK</label><input id="eNik" class="form-control" placeholder="Example: SM0807"></div><button id="eSearch" class="btn btn-primary"><i class="mdi mdi-magnify me-1"></i>Search History</button></div>
<div id="eEmpty" class="mc-panel"><div class="mc-empty"><i class="mdi mdi-account-search-outline"></i><div>Enter an employee NIK to display meal history.</div></div></div>
<div id="eResult" style="display:none"><div class="mc-stat-grid"><div class="mc-stat-card"><div class="mc-stat-label">Total Portions</div><div id="eTotal" class="mc-stat-value">—</div></div><div class="mc-stat-card is-success"><div class="mc-stat-label">Breakfast</div><div id="eBreakfast" class="mc-stat-value">—</div></div><div class="mc-stat-card is-orange"><div class="mc-stat-label">Lunch</div><div id="eLunch" class="mc-stat-value">—</div></div><div class="mc-stat-card is-cyan"><div class="mc-stat-label">Dinner</div><div id="eDinner" class="mc-stat-value">—</div></div></div><div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title" id="eTitle">Meal History</div><div class="mc-panel-subtitle" id="eMeta"></div></div></div><div class="table-responsive"><table class="mc-table-modern"><thead><tr><th>Date / Time</th><th>Meal</th><th>Order Type</th><th>Qty</th><th>Rating</th><th>Location</th><th>Created By</th></tr></thead><tbody id="eBody"></tbody></table></div></div></div>
</div></div>
<script>const ee=v=>$('<div>').text(v??'').html();function loadE(){const nik=$('#eNik').val().trim();if(!nik)return;fetch(`{{ route('reports.employeeHistory.api') }}?nik=${encodeURIComponent(nik)}`).then(r=>r.json()).then(d=>{$('#eEmpty').hide();$('#eResult').show();$('#eTitle').text(`Meal History · ${d.nik}`);$('#eTotal').text(d.summary.total);$('#eBreakfast').text(d.summary.breakfast);$('#eLunch').text(d.summary.lunch);$('#eDinner').text(d.summary.dinner);$('#eMeta').text(`${d.summary.transactions} records · Avg rating ${Number(d.summary.average_rating||0).toFixed(1)}`);$('#eBody').html(d.records.length?d.records.map(x=>`<tr><td>${ee(x.attendance_date)}<div class="text-muted" style="font-size:9px">${x.attendance_time?new Date(x.attendance_time).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):''}</div></td><td>${ee(x.meal_type)}</td><td>${ee(x.order_type||'—')}</td><td>${x.quantity}</td><td>${Number(x.rating||0)>0?`<span class="mc-stars">★</span> ${x.rating}`:'—'}</td><td>${ee(x.position||'—')}</td><td>${ee(x.created_by||'—')}</td></tr>`).join(''):'<tr><td colspan="7"><div class="mc-empty">No history found for this NIK.</div></td></tr>');});}$('#eSearch').click(loadE);$('#eNik').on('keydown',e=>{if(e.key==='Enter')loadE()});</script>
@include('layout.footer')
