@include('layout.head')
@include('layout.topbar')
@include('layout.sidebar')
<div class="content"><div class="container-fluid">
<div class="mc-page-header"><div><h1 class="mc-page-title">Monthly Report</h1><p class="mc-page-subtitle">Rekap per hari untuk satu bulan, tetap menggunakan export Excel lama.</p></div><div class="mc-page-actions"><a id="mExport" href="#" class="btn btn-primary"><i class="mdi mdi-microsoft-excel me-1"></i>Export Existing Excel</a></div></div>
<div class="mc-filterbar"><div class="mc-filter-field"><label class="mc-filter-label">Month</label><input id="mMonth" type="month" class="form-control" value="{{ now()->format('Y-m') }}"></div><button id="mApply" class="btn btn-primary">Generate</button></div>
<div class="mc-stat-grid"><div class="mc-stat-card"><div class="mc-stat-label">Monthly Portions</div><div id="mTotal" class="mc-stat-value">—</div><div class="mc-stat-meta">All sessions</div></div><div class="mc-stat-card is-success"><div class="mc-stat-label">Breakfast</div><div id="mBreakfast" class="mc-stat-value">—</div></div><div class="mc-stat-card is-orange"><div class="mc-stat-label">Lunch</div><div id="mLunch" class="mc-stat-value">—</div></div><div class="mc-stat-card is-cyan"><div class="mc-stat-label">Dinner</div><div id="mDinner" class="mc-stat-value">—</div></div></div>
<div class="mc-grid-2"><div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Daily Trend</div><div class="mc-panel-subtitle">Meal portions by date</div></div></div><div class="mc-panel-body"><div id="monthlyChart"></div></div></div><div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Daily Summary</div><div class="mc-panel-subtitle">Compact monthly table</div></div></div><div class="table-responsive"><table class="mc-table-modern"><thead><tr><th>Date</th><th>Total</th><th>B</th><th>L</th><th>D</th></tr></thead><tbody id="mBody"></tbody></table></div></div></div>
</div></div>
<script src="{{ asset('admin/dist') }}/assets/libs/apexcharts/apexcharts.min.js"></script><script>let mc;function loadM(){const month=$('#mMonth').val();const start=`${month}-01`;const dt=new Date(`${month}-01T00:00:00`);const end=new Date(dt.getFullYear(),dt.getMonth()+1,0);const endStr=`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,'0')}-${String(end.getDate()).padStart(2,'0')}`;$('#mExport').attr('href',`{{ route('consumptionData.export') }}?period=${encodeURIComponent(start+' to '+endStr)}`);fetch(`{{ route('reports.monthly.api') }}?month=${encodeURIComponent(month)}`).then(r=>r.json()).then(d=>{$('#mTotal').text(d.summary.total);$('#mBreakfast').text(d.summary.breakfast);$('#mLunch').text(d.summary.lunch);$('#mDinner').text(d.summary.dinner);$('#mBody').html(d.daily.length?d.daily.map(x=>`<tr><td>${x.date}</td><td><strong>${x.total}</strong></td><td>${x.breakfast}</td><td>${x.lunch}</td><td>${x.dinner}</td></tr>`).join(''):'<tr><td colspan="5"><div class="mc-empty">No monthly data</div></td></tr>');if(mc)mc.destroy();mc=new ApexCharts(document.querySelector('#monthlyChart'),{chart:{type:'area',height:360,toolbar:{show:false}},series:[{name:'Breakfast',data:d.daily.map(x=>x.breakfast)},{name:'Lunch',data:d.daily.map(x=>x.lunch)},{name:'Dinner',data:d.daily.map(x=>x.dinner)}],xaxis:{categories:d.daily.map(x=>x.date.slice(-2))},stroke:{curve:'smooth',width:2},colors:['#16a34a','#ea580c','#0891b2'],dataLabels:{enabled:false},legend:{position:'top'},fill:{type:'gradient',gradient:{opacityFrom:.16,opacityTo:.02}}});mc.render();});}$('#mApply').click(loadM);loadM();</script>
@include('layout.footer')
