@include('layout.head')
@include('layout.topbar')
@include('layout.sidebar')
<div class="content"><div class="container-fluid">
<div class="mc-page-header"><div><h1 class="mc-page-title">Order Type Analysis</h1><p class="mc-page-subtitle">Bandingkan pola Dine In, Take Away, Menu Sehat, dan order type lainnya.</p></div></div>
<div class="mc-filterbar"><div class="mc-filter-field"><label class="mc-filter-label">From</label><input id="oFrom" type="date" class="form-control" value="{{ now()->subDays(6)->format('Y-m-d') }}"></div><div class="mc-filter-field"><label class="mc-filter-label">To</label><input id="oTo" type="date" class="form-control" value="{{ now()->format('Y-m-d') }}"></div><button id="oApply" class="btn btn-primary">Analyze</button></div>
<div class="mc-grid-2">
<div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Order Type Distribution</div><div class="mc-panel-subtitle">Portion share in selected period</div></div></div><div class="mc-panel-body"><div id="orderDonut"></div></div></div>
<div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Meal Type vs Order Type</div><div class="mc-panel-subtitle">Composition inside each meal session</div></div></div><div class="mc-panel-body" id="orderMatrix"></div></div>
</div></div></div>
<script src="{{ asset('admin/dist') }}/assets/libs/apexcharts/apexcharts.min.js"></script>
<script>let od;const esc=v=>$('<div>').text(v??'').html();const nf=new Intl.NumberFormat('id-ID');function loadO(){const q=new URLSearchParams({from:$('#oFrom').val(),to:$('#oTo').val()});fetch(`{{ route('analytics.api') }}?${q}`).then(r=>r.json()).then(d=>{if(od)od.destroy();od=new ApexCharts(document.querySelector('#orderDonut'),{chart:{type:'donut',height:360},series:d.order_types.map(x=>x.total),labels:d.order_types.map(x=>x.name),colors:['#2563eb','#f59e0b','#7c3aed','#0891b2','#16a34a'],dataLabels:{enabled:false},legend:{position:'bottom'},plotOptions:{pie:{donut:{size:'68%',labels:{show:true,total:{show:true,label:'Orders',formatter:()=>nf.format(d.summary.total)}}}}}});od.render();$('#orderMatrix').html(d.meal_order_matrix.map(m=>{const t=m.types.reduce((s,x)=>s+Number(x.total),0)||1;return `<div class="mb-4"><div class="d-flex justify-content-between mb-2"><strong style="font-size:11px;color:#334155">${esc(m.meal)}</strong><span class="text-muted" style="font-size:10px">${nf.format(t)} portions</span></div>${m.types.map(x=>`<div class="mc-progress-row"><div class="mc-progress-name">${esc(x.name)}</div><div class="mc-progress-track"><div class="mc-progress-fill" style="width:${Number(x.total)/t*100}%"></div></div><div class="mc-progress-value">${(Number(x.total)/t*100).toFixed(1)}%</div></div>`).join('')||'<div class="text-muted">No data</div>'}</div>`}).join(''));});}$('#oApply').click(loadO);loadO();</script>
@include('layout.footer')
