@include('layout.head')
@include('layout.topbar')
@include('layout.sidebar')
<div class="content"><div class="container-fluid">
<div class="mc-page-header"><div><h1 class="mc-page-title">Rating & Feedback</h1><p class="mc-page-subtitle">Pantau kepuasan makan berdasarkan rating yang masuk pada attendance log.</p></div></div>
<div class="mc-filterbar"><div class="mc-filter-field"><label class="mc-filter-label">From</label><input id="rFrom" type="date" class="form-control" value="{{ now()->subDays(29)->format('Y-m-d') }}"></div><div class="mc-filter-field"><label class="mc-filter-label">To</label><input id="rTo" type="date" class="form-control" value="{{ now()->format('Y-m-d') }}"></div><button id="rApply" class="btn btn-primary">Refresh</button></div>
<div class="mc-stat-grid"><div class="mc-stat-card is-orange"><div class="mc-stat-label">Average Rating</div><div class="mc-stat-value" id="rAvg">—</div><div class="mc-stat-meta">Out of 5</div></div><div class="mc-stat-card"><div class="mc-stat-label">Rated Transactions</div><div class="mc-stat-value" id="rCount">—</div><div class="mc-stat-meta">With rating > 0</div></div><div class="mc-stat-card is-success"><div class="mc-stat-label">5 Star</div><div class="mc-stat-value" id="rFive">—</div><div class="mc-stat-meta">Excellent feedback</div></div><div class="mc-stat-card is-danger"><div class="mc-stat-label">1–2 Star</div><div class="mc-stat-value" id="rLow">—</div><div class="mc-stat-meta">Needs attention</div></div></div>
<div class="mc-grid-2"><div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Rating Distribution</div><div class="mc-panel-subtitle">Count by star</div></div></div><div class="mc-panel-body"><div id="ratingChart"></div></div></div><div class="mc-panel"><div class="mc-panel-head"><div><div class="mc-panel-title">Recent Feedback</div><div class="mc-panel-subtitle">Latest rated transactions</div></div></div><div class="table-responsive"><table class="mc-table-modern"><thead><tr><th>Date</th><th>NIK</th><th>Meal</th><th>Rating</th><th>Remarks</th></tr></thead><tbody id="rBody"></tbody></table></div></div></div>
</div></div>
<script src="{{ asset('admin/dist') }}/assets/libs/apexcharts/apexcharts.min.js"></script><script>let rc;const esc=v=>$('<div>').text(v??'').html();function stars(n){return '★'.repeat(Math.max(0,Math.min(5,Math.round(Number(n||0)))))}function loadR(){const q=new URLSearchParams({from:$('#rFrom').val(),to:$('#rTo').val()});fetch(`{{ route('analytics.api') }}?${q}`).then(r=>r.json()).then(d=>{const dist=d.rating_distribution;$('#rAvg').text(Number(d.summary.average_rating||0).toFixed(1));$('#rCount').text(d.summary.rated_count);$('#rFive').text(dist.find(x=>x.rating===5)?.total||0);$('#rLow').text((dist.find(x=>x.rating===1)?.total||0)+(dist.find(x=>x.rating===2)?.total||0));$('#rBody').html(d.recent_ratings.length?d.recent_ratings.map(x=>`<tr><td>${esc(x.attendance_date)}</td><td><strong>${esc(x.nik)}</strong></td><td><span class="mc-status orange">${esc(x.meal_type)}</span></td><td><span class="mc-stars">${stars(x.rating)}</span> ${Number(x.rating).toFixed(0)}</td><td>${esc(x.remarks||'—')}</td></tr>`).join(''):'<tr><td colspan="5"><div class="mc-empty">No rating data</div></td></tr>');if(rc)rc.destroy();rc=new ApexCharts(document.querySelector('#ratingChart'),{chart:{type:'bar',height:330,toolbar:{show:false}},series:[{name:'Reviews',data:dist.map(x=>x.total)}],xaxis:{categories:dist.map(x=>`${x.rating} Star`)},plotOptions:{bar:{borderRadius:7,columnWidth:'48%'}},colors:['#f59e0b'],dataLabels:{enabled:false}});rc.render();});}$('#rApply').click(loadR);loadR();</script>
@include('layout.footer')
